services:
    postgres:
      image: postgres:16
      container_name: postgres
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: pass
        POSTGRES_DB: mydb
      networks:
        - my-network
    back:
      build: 
        context: ./back
      container_name: pyhton-client
      depends_on:
        - postgres 
      ports:
        - "8081:5000"
      networks:
      - my-network
      volumes:
      - ./back/app.py:/app/app.py
      restart: unless-stopped 
networks:
  my-network:
    driver: bridge
